const $=s=>document.querySelector(s),fresh=()=>({index:0,selected:null,score:0,streak:0,wrongChain:0,health:100,spo2:98,pulse:72,focus:100,answered:false,review:[],records:[],symptoms:[],anatomyEpisodes:[],affectedRegions:[]}),state=fresh();
const el={conditionText:$("#conditionText"),conditionDetail:$("#conditionDetail"),spo2:$("#spo2"),pulse:$("#pulse"),focus:$("#focus"),healthValue:$("#healthValue"),healthBar:$("#healthBar"),caseNumber:$("#caseNumber"),caseTotal:$("#caseTotal"),progressBar:$("#progressBar"),category:$("#category"),difficulty:$("#difficulty"),streak:$("#streak"),sourceBadge:$("#sourceBadge"),scenario:$("#scenario"),question:$("#question"),choices:$("#choices"),feedback:$("#feedback"),feedbackIcon:$("#feedbackIcon"),feedbackLabel:$("#feedbackLabel"),feedbackTitle:$("#feedbackTitle"),feedbackText:$("#feedbackText"),consequence:$("#consequence"),choiceNotes:$("#choiceNotes"),detailBox:$("#detailBox"),submit:$("#submitButton"),next:$("#nextButton"),modal:$("#resultModal"),avatarStage:$("#avatarStage"),avatarState:$("#avatarState"),avatarCallout:$("#avatarCallout"),symptomChips:$("#symptomChips"),recordLog:$("#recordLog"),recordCount:$("#recordCount")};
let soundOn=false,audioContext=null,fullBank=[...QUESTION_BANK];
function tone(freq,duration,type="sine",delay=0){if(!soundOn)return;audioContext??=new(window.AudioContext||window.webkitAudioContext)();let o=audioContext.createOscillator(),g=audioContext.createGain(),t=audioContext.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.12,t+.02);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g).connect(audioContext.destination);o.start(t);o.stop(t+duration)}
function sound(kind){if(kind==="ok"){tone(520,.15);tone(720,.2,"sine",.12)}else if(kind==="wrong"){tone(180,.35,"sawtooth");tone(120,.45,"sawtooth",.18)}else{tone(260,.15,"square");tone(220,.15,"square",.22);tone(180,.8,"sawtooth",.44)}}
function shuffle(list){for(let i=list.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[list[i],list[j]]=[list[j],list[i]]}return list}
function render(){let q=QUESTION_BANK[state.index];state.selected=null;state.answered=false;document.body.className="";el.caseNumber.textContent=String(state.index+1).padStart(2,"0");el.caseTotal.textContent=`/ ${QUESTION_BANK.length}`;el.progressBar.style.width=`${(state.index+1)/QUESTION_BANK.length*100}%`;el.category.textContent=q.category;el.difficulty.textContent="●".repeat(q.difficulty)+"○".repeat(3-q.difficulty);el.sourceBadge.textContent=q.source;el.scenario.textContent=q.scenario;el.question.textContent=q.question;el.choices.innerHTML="";q.choices.forEach((c,i)=>{let b=document.createElement("button");b.className="choice";b.innerHTML=`<span class="choice-index">${i+1}</span><span>${c}</span>`;b.onclick=()=>select(i);el.choices.appendChild(b)});el.feedback.className="feedback";el.detailBox.open=false;el.submit.hidden=false;el.submit.disabled=true;el.next.hidden=true;status();avatar(null)}
function select(i){if(state.answered||i>=QUESTION_BANK[state.index].choices.length)return;state.selected=i;[...el.choices.children].forEach((b,n)=>b.classList.toggle("selected",n===i));el.submit.disabled=false}
function submit(){if(state.selected===null||state.answered)return;state.answered=true;let q=QUESTION_BANK[state.index],ok=state.selected===q.answer,e=q.effect,multiplier=1,damage=0;[...el.choices.children].forEach((b,i)=>{b.disabled=true;if(i===q.answer)b.classList.add("correct");if(i===state.selected&&!ok)b.classList.add("wrong")});if(ok){state.score++;state.streak++;state.wrongChain=0;let heal=state.streak>=2?3:0;state.health=Math.min(100,state.health+heal);state.focus=Math.min(100,state.focus+4);el.feedback.className="feedback show correct-feedback";el.feedbackIcon.textContent="✓";el.feedbackLabel.textContent="CORRECT ASSESSMENT";el.feedbackTitle.textContent="判断は適切です";el.consequence.textContent=heal?`連続正解：体調が ${heal} 回復した。`:"病態の逆流を防いだ。"}else{state.streak=0;state.wrongChain++;multiplier=1+(state.wrongChain-1)*.5;damage=Math.round(e.damage*multiplier);state.review.push(q.id);state.health=Math.max(0,state.health-damage);state.spo2=Math.max(70,state.spo2+e.spo2-(state.wrongChain-1)*2);state.pulse=Math.min(180,state.pulse+e.pulse+(state.wrongChain-1)*5);state.focus=Math.max(5,state.focus-e.focus-(state.wrongChain-1)*4);state.symptoms.push(e.name);document.body.className=e.className;el.feedback.className="feedback show";el.feedbackIcon.textContent="!";el.feedbackLabel.textContent=state.wrongChain>=2?"MULTIPLE ORGAN FAILURE RISK":"CONDITION TRANSFERRED";el.feedbackTitle.textContent=`${e.name}があなたに発現した`;el.consequence.textContent=`−${damage} CONDITION${state.wrongChain>1?`（連続ミス ×${multiplier.toFixed(1)}）`:""}｜${e.detail}`;el.conditionText.textContent=e.name;el.conditionDetail.textContent=e.detail}state.records.unshift({caseNo:state.index+1,quote:q.choices[state.selected],ok,result:ok?"適切な判断。病態の逆流を防いだ":`${e.name}：${e.detail}${state.wrongChain>1?`／連続ミス×${multiplier.toFixed(1)}`:""}`});records();avatar(ok?null:e);el.feedbackText.textContent=q.explanation;el.choiceNotes.innerHTML=q.notes.map((n,i)=>`<p><b>${i+1}.</b> ${n}</p>`).join("");el.submit.hidden=true;el.next.hidden=false;el.streak.textContent=state.streak;status();if(!ok){el.avatarStage.classList.add("danger-flash");setTimeout(()=>el.avatarStage.classList.remove("danger-flash"),1400)}if(state.health<=0)setTimeout(death,850)}
function status(){el.healthValue.textContent=state.health;el.healthBar.style.width=`${state.health}%`;el.healthBar.style.background=state.health<40?"#d94b4b":state.health<70?"#d98a32":"#69d5c1";el.spo2.textContent=state.spo2;el.pulse.textContent=state.pulse;el.focus.textContent=state.focus;if(state.health===100){el.conditionText.textContent="安定";el.conditionDetail.textContent="異常所見なし"}else if(!state.answered){el.conditionText.textContent=state.health<40?"危険":"経過観察";el.conditionDetail.textContent=state.health<40?"複数の症状が生命を脅かしている":"前の症状が残っている"}}
function records(){el.recordCount.textContent=`${state.records.length}件`;el.recordLog.innerHTML=state.records.map(r=>`<article class="record-item ${r.ok?"":"wrong-record"}"><small>CASE ${String(r.caseNo).padStart(2,"0")} · ${r.ok?"適切":"誤った判断"}</small><p>${r.quote}</p><b>${r.result}</b></article>`).join("")}
function avatar(e){let c=[];for(const s of state.symptoms){if(/低酸素|気道/.test(s))c.push("hypoxia-avatar","show-chest");if(/不整脈/.test(s))c.push("arrhythmia-avatar","show-chest");if(/関節/.test(s))c.push("joint-avatar","show-limb");if(/神経/.test(s))c.push("nerve-avatar","show-limb");if(/筋力/.test(s))c.push("weak-avatar","show-limb");if(/老廃物|情報/.test(s))c.push("blur-avatar","show-head")}if(state.health<45)c.push("severe","tremor-avatar");el.avatarStage.className=`avatar-stage ${[...new Set(c)].join(" ")}`;if(e){el.avatarState.textContent=state.health<45?"CRITICAL":"SYMPTOM DETECTED";el.avatarCallout.innerHTML=`<b>${e.name}</b><span>${e.detail}</span>`}else if(state.symptoms.length){el.avatarState.textContent=state.health<45?"CRITICAL":"UNSTABLE";el.avatarCallout.innerHTML=`<b>${state.symptoms.at(-1)}</b><span>症状が残存・累積中</span>`}else{el.avatarState.textContent="STABLE";el.avatarCallout.innerHTML="<b>正常</b><span>症状はありません</span>"}el.symptomChips.innerHTML=state.symptoms.length?[...new Set(state.symptoms)].map(s=>`<span>${s}</span>`).join(""):"<span class=\"empty-chip\">状態異常なし</span>"}
function next(){state.index<QUESTION_BANK.length-1?(state.index++,render()):finish()}
function finish(){$("#finalScore").textContent=state.score;$("#finalHealth").textContent=state.health;$("#reviewCount").textContent=state.review.length;$("#resultMessage").textContent=state.score>=8?"病態の連鎖を断ち切りました。":state.score>=5?"夜勤完了。誤答症例を確認しましょう。":"症状が蓄積しました。再挑戦しましょう。";el.modal.hidden=false;save()}
function death(){el.avatarStage.className="avatar-stage dead-avatar show-head show-chest";el.avatarState.textContent="NO VITAL SIGNS";el.avatarCallout.innerHTML="<b>心肺停止</b><span>判断ミスが致命的な結果を招いた</span>";$("#resultCard").classList.add("death");$("#resultEyebrow").textContent="CODE BLUE";$("#resultTitle").textContent="心肺停止";$("#finalScore").textContent=state.score;$("#finalHealth").textContent=0;$("#reviewCount").textContent=state.review.length;$("#resultMessage").textContent="誤った判断が重なり、勤務を継続できなくなりました。記録から原因を確認してください。";el.modal.hidden=false;save()}
function save(){localStorage.setItem("recare-last",JSON.stringify({score:state.score,review:state.review,records:state.records,date:new Date().toISOString()}))}
function reset(){Object.assign(state,fresh());el.modal.hidden=true;$("#resultCard").classList.remove("death");$("#resultEyebrow").textContent="SHIFT COMPLETE";$("#resultTitle").textContent="夜勤終了";el.recordLog.innerHTML='<p class="empty-record">判断すると、選んだ発言と身体に起きたことがここに記録されます。</p>';el.recordCount.textContent="0件";render()}
function openReport(){let q=QUESTION_BANK[state.index];$("#reportQuestion").textContent=`${q.source}｜${q.question}`;$("#reportMessage").value="";$("#reportStatus").textContent="";$("#reportModal").hidden=false}
function closeReport(){$("#reportModal").hidden=true}
function sendReport(event){event.preventDefault();let q=QUESTION_BANK[state.index],report={reportedAt:new Date().toISOString(),questionId:q.id,source:q.source,question:q.question,selectedAnswer:state.selected===null?"未回答":q.choices[state.selected],officialAnswer:q.choices[q.answer],explanation:q.explanation,type:$("#reportType").value,message:$("#reportMessage").value.trim(),replyTo:$("#reportReply").value.trim()},saved=JSON.parse(localStorage.getItem("recare-feedback")||"[]");saved.push(report);localStorage.setItem("recare-feedback",JSON.stringify(saved));let recipient=window.RECARE_CONFIG?.feedbackEmail||"",subject=encodeURIComponent(`[RE:CARE 誤り報告] ${q.id} ${report.type}`),body=encodeURIComponent(`問題: ${report.questionId}\n出典: ${report.source}\n種別: ${report.type}\n報告: ${report.message}\n選択回答: ${report.selectedAnswer}\n正答表示: ${report.officialAnswer}\n現在の解説: ${report.explanation}\n返信先: ${report.replyTo||"なし"}\n報告日時: ${report.reportedAt}`);if(recipient){$("#reportStatus").textContent="メール作成画面を開きます。端末にも控えを保存しました。";location.href=`mailto:${encodeURIComponent(recipient)}?subject=${subject}&body=${body}`}else{$("#reportStatus").textContent="端末に報告を保存しました。管理者の受信用メールは設定待ちです。"}}
el.submit.onclick=submit;el.next.onclick=next;$("#resetButton").onclick=reset;$("#retryButton").onclick=reset;$("#reportButton").onclick=openReport;$("#reportClose").onclick=closeReport;$("#reportForm").onsubmit=sendReport;$("#reportModal").onclick=e=>{if(e.target.id==="reportModal")closeReport()};$("#soundButton").onclick=e=>e.currentTarget.textContent=e.currentTarget.textContent==="◌"?"●":"◌";document.addEventListener("keydown",e=>{if(e.key==="Escape")closeReport();if(e.key>="1"&&e.key<="5")select(+e.key-1);if(e.key==="Enter"&&!$("#reportModal").hidden)return;if(e.key==="Enter")state.answered?next():submit()});render();
