(()=>{
const USERS="recare-local-accounts",ACTIVE="recare-active-user";
const normalize=s=>s.trim().toLowerCase(),escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function hash(text){let data=new TextEncoder().encode(`RECARE:${text}:LOCAL`),digest=await crypto.subtle.digest("SHA-256",data);return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function accounts(){try{return JSON.parse(localStorage.getItem(USERS))||{}}catch{return{}}}
function gate(){document.body.insertAdjacentHTML("afterbegin",`<section class="auth-gate" id="authGate"><div class="auth-grid"></div><form class="auth-card" id="authForm"><div class="auth-brand">RE:<span>CARE</span></div><h1>病棟端末にログイン</h1><p class="auth-lead">ユーザーネームと4桁コードで、あなたの学習記録を呼び出します。初めての名前は自動登録されます。</p><label>USER NAME<input id="loginName" autocomplete="username" maxlength="20" required placeholder="例：nurse01"></label><label>4-DIGIT CODE<div class="pin-wrap"><input id="loginPin" type="password" inputmode="numeric" autocomplete="current-password" pattern="[0-9]{4}" maxlength="4" required placeholder="••••"><button type="button" id="pinReveal" aria-label="コードを表示">表示</button></div></label><button class="auth-submit" type="submit">LOGIN / REGISTER →</button><p class="auth-message" id="authMessage"></p><p class="auth-note">このログインはこの端末内だけで使用されます。4桁コードを忘れた場合の復旧や、別端末との同期には対応していません。</p></form></section>`);let pin=$("#loginPin");$("#pinReveal").onclick=()=>{pin.type=pin.type==="password"?"text":"password";$("#pinReveal").textContent=pin.type==="password"?"表示":"隠す"};$("#authForm").onsubmit=login}
async function login(e){e.preventDefault();let button=e.currentTarget.querySelector(".auth-submit"),display=$("#loginName").value.trim(),key=normalize(display),pin=$("#loginPin").value;if(!/^[0-9]{4}$/.test(pin)){$("#authMessage").textContent="4桁の数字を入力してください。";return}if(!/^[\p{L}\p{N}_-]{2,20}$/u.test(display)){$("#authMessage").textContent="名前は2〜20文字の英数字・日本語・_・-で入力してください。";return}button.disabled=true;$("#authMessage").textContent="学習記録を確認しています…";let db=accounts(),codeHash=await hash(`${key}:${pin}`);try{if(window.RECARE_CLOUD?.enabled()){let result=await window.RECARE_CLOUD.login(key,pin,display);db[key]={name:result.session.displayName,hash:codeHash,cloud:true};localStorage.setItem(USERS,JSON.stringify(db));localStorage.setItem(`recare-profile-v1:${key}`,JSON.stringify(result.profile));localStorage.setItem(ACTIVE,key);location.reload();return}if(db[key]&&db[key].hash!==codeHash)throw new Error("4桁コードが違います。");if(!db[key]){db[key]={name:display,hash:codeHash,createdAt:new Date().toISOString()};localStorage.setItem(USERS,JSON.stringify(db));let legacy=localStorage.getItem("recare-profile-v1");if(legacy&&!localStorage.getItem(`recare-profile-v1:${key}`))localStorage.setItem(`recare-profile-v1:${key}`,legacy)}localStorage.setItem(ACTIVE,key);location.reload()}catch(error){$("#authMessage").textContent=error.message;button.disabled=false}}
function accountUI(key){let db=accounts(),name=db[key]?.name||key,top=document.querySelector(".topbar");top?.insertAdjacentHTML("beforeend",`<button class="account-chip" id="accountMenuButton" type="button" aria-label="マイページを開く"><i>${escapeHTML(name.slice(0,1).toUpperCase())}</i><span>${escapeHTML(name)}</span><small>MY PAGE</small></button>`);document.querySelector(".title-actions")?.insertAdjacentHTML("beforebegin",`<p class="welcome-user">SIGNED IN AS <b>${escapeHTML(name)}</b>${window.RECARE_CLOUD?.enabled()?" · CLOUD SYNC":" · THIS DEVICE"}</p>`)}
let active=localStorage.getItem(ACTIVE);if(active&&accounts()[active])accountUI(active);else{localStorage.removeItem(ACTIVE);gate()}
})();
