(()=>{
const escapeHTML=value=>String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const rules=[
 {re:/呼吸|低酸素|気道|喘息|肺|SpO2|チアノーゼ|息|酸素/,zone:"chest",label:"肺・気道",skin:"",items:["息苦しさ・呼吸数の増加","口唇の紫色変化（チアノーゼ）","会話困難・意識低下"]},
 {re:/心|循環|不整脈|狭心|脈|血圧|ショック|胸部/,zone:"chest",label:"心臓・循環",skin:"pale",items:["動悸・胸部不快感","冷汗・顔面蒼白","めまい・意識消失"]},
 {re:/脳|神経|意識|構音|めまい|耳鳴|けいれん|麻痺/,zone:"head",label:"脳・神経",skin:"",items:["意識・見当識の変化","ろれつ困難・片側の麻痺","めまい・ふらつき"]},
 {re:/肝|黄疸|胆|消化|嘔吐|腹|胃|腸|膵/,zone:"abdomen",label:"腹部・消化器",skin:"jaundice",items:["腹痛・腹部膨満","悪心・嘔吐・食欲低下","皮膚や眼球の黄染"]},
 {re:/腎|尿|乏尿|老廃物|浮腫|電解質/,zone:"abdomen",label:"腎・泌尿器",skin:"pale",items:["尿量・尿の性状の変化","むくみ・体重増加","倦怠感・意識変化"]},
 {re:/感染|発熱|水痘|発疹|炎|中毒|アレルギー|免疫/,zone:"head",label:"全身・皮膚",skin:"rash",items:["発熱・悪寒・発汗","発疹・皮膚の変化","頻脈・全身倦怠感"]},
 {re:/筋|関節|痛|しびれ|運動|骨|麻痺/,zone:"limb",label:"四肢・運動",skin:"",items:["痛み・しびれ","筋力低下・動作困難","歩行や姿勢の変化"]},
 {re:/糖|甲状腺|内分泌|代謝|血糖/,zone:"head",label:"代謝・全身",skin:"pale",items:["強い倦怠感・脱力","発汗・動悸・意識変化","口渇・体重変化"]}
];
function classify(effect,q){let text=`${effect?.name||""} ${effect?.detail||""} ${q?.category||""}`;return rules.find(r=>r.re.test(text))||{zone:"head",label:"全身状態",skin:"pale",items:["倦怠感・集中力低下","バイタルサインの変化","症状の進行に伴う意識変化"]}}
function detailItems(effect,profile){let direct=String(effect?.detail||"").split(/[・、,／。]/).map(x=>x.trim()).filter(x=>x.length>2);return [...new Set([...direct,...profile.items])].slice(0,3)}
function ensureUI(){if(!document.querySelector(".clinical-overlay")){el.avatarStage.insertAdjacentHTML("beforeend",`<div class="clinical-overlay"><div class="organ-marker zone-head">脳・意識</div><div class="organ-marker zone-chest">呼吸・循環</div><div class="organ-marker zone-abdomen">腹部・代謝</div><div class="organ-marker zone-limb">疼痛・運動</div></div>`);el.symptomChips.insertAdjacentHTML("afterend",`<section class="clinical-card" id="clinicalCard"><div class="clinical-card-head"><b>実際に観察する症状</b><span class="severity-pill" id="clinicalSeverity">NORMAL</span></div><ul class="clinical-list" id="clinicalList"><li><i>✓</i><div><b>異常所見なし</b><span>呼吸・意識・皮膚色・運動状態は安定</span></div></li></ul><div class="clinical-note" id="clinicalNote">誤答時に、その病態で現れやすい症状と観察部位を表示します。</div></section>`);document.body.insertAdjacentHTML("beforeend",`<button class="mobile-symptom-dock" id="mobileSymptomDock" type="button"></button>`);$("#mobileSymptomDock").onclick=()=>{el.avatarStage.scrollIntoView({behavior:"smooth",block:"center"});$("#mobileSymptomDock").classList.remove("show")}}}
const baseAvatar=avatar;
avatar=function(effect){baseAvatar(effect);ensureUI();let stage=el.avatarStage,dock=$("#mobileSymptomDock"),card=$("#clinicalCard");stage.classList.remove("symptomatic","zone-head","zone-chest","zone-abdomen","zone-limb","skin-jaundice","skin-rash","skin-pale");if(!effect){if(!state.symptoms.length){$("#clinicalSeverity").textContent="NORMAL";$("#clinicalList").innerHTML='<li><i>✓</i><div><b>異常所見なし</b><span>呼吸・意識・皮膚色・運動状態は安定</span></div></li>';$("#clinicalNote").textContent="誤答時に、その病態で現れやすい症状と観察部位を表示します。";dock.classList.remove("show")}return}let q=QUESTION_BANK[state.index],p=classify(effect,q),items=detailItems(effect,p),severity=state.health<45?"CRITICAL":effect.damage>=22?"SEVERE":"MODERATE";stage.classList.add("symptomatic",`zone-${p.zone}`,...(p.skin?[`skin-${p.skin}`]:[]));$("#clinicalSeverity").textContent=severity;$("#clinicalList").innerHTML=items.map((x,i)=>`<li><i>${i+1}</i><div><b>${escapeHTML(x)}</b><span>${i===0?`主症状として観察する`:i===1?`同時に確認する随伴症状`:`悪化時に注意する徴候`}</span></div></li>`).join("");$("#clinicalNote").innerHTML=`<b>${escapeHTML(p.label)}</b>を強調表示中。数値だけでなく、本人の訴え・表情・皮膚色・動作を合わせて観察します。`;dock.innerHTML=`${escapeHTML(effect.name)}<small>${escapeHTML(effect.detail)}｜${escapeHTML(p.label)}に所見</small>`;if(matchMedia("(max-width:760px)").matches){dock.classList.add("show");setTimeout(()=>dock.classList.remove("show"),6500)}card.classList.add("active")};
ensureUI();avatar(null);
})();
