(()=>{
const LIFE=/心停止|心肺停止|窒息|アナフィラキシー|大動脈解離|心タンポナーデ|緊張性気胸|肺血栓塞栓|ARDS|敗血症|DIC|播種性血管内凝固|くも膜下出血|急性心筋梗塞|気道閉塞|大量出血|死戦期/;
const CRITICAL=/脳梗塞|脳卒中|髄膜炎|糖尿病性ケトアシドーシス|DKA|急性腎不全|急性腎障害|狭心症|有機リン|破傷風|けいれん|意識障害|呼吸不全|低酸素血症|血圧低下|臓器障害|高カリウム|低ナトリウム|喀血|吐血/;
const MODERATE=/肺炎|喘息|COPD|心不全|不整脈|心房細動|感染|脱水|貧血|黄疸|肝炎|腎機能|浮腫|高血圧|低血糖|甲状腺|嘔吐|下痢|発熱|麻痺|尿閉|出血傾向|血小板|白血病/;
function riskOf(effect,q){q=q||QUESTION_BANK?.[state.index];let text=`${q?.question||""} ${q?.explanation||""} ${q?.scenario||""} ${effect.name} ${effect.detail}`;if(LIFE.test(text))return{key:"life",label:"生命危機",damage:45,color:"#9d1527",note:"直ちに救命処置と応援要請が必要"};if(CRITICAL.test(text))return{key:"critical",label:"重症",damage:32,color:"#d33243",note:"急速な悪化に警戒し、緊急対応が必要"};if(MODERATE.test(text))return{key:"moderate",label:"中等症",damage:20,color:"#e0782e",note:"継続観察と早期対応が必要"};return{key:"mild",label:"軽症",damage:10,color:"#d3a12d",note:"生命危機は低いが症状観察が必要"}}
function impact(effect,risk,before){document.querySelector(".damage-impact")?.remove();let after=Math.max(0,before-risk.damage),node=document.createElement("div");node.className=`damage-impact impact-${risk.key}`;node.innerHTML=`<div class="damage-impact-core"><header><span>PATHOLOGY LINK / ${risk.key.toUpperCase()}</span><span>耐性 ${before} → ${after}</span></header><strong>${risk.label} <em>−${risk.damage}</em></strong><p>${effect.name}｜${effect.detail}</p><div class="vital-delta"><span>SpO₂ <b>${state.spo2}%</b></span><span>PULSE <b>${state.pulse}</b></span><span>FOCUS <b>${state.focus}%</b></span></div></div>`;document.body.appendChild(node);document.querySelector(".status-strip")?.classList.add("vital-alarm");setTimeout(()=>{node.remove();document.querySelector(".status-strip")?.classList.remove("vital-alarm")},1300)}
const previousSubmit=submit;
submit=function(){if(state.selected===null||state.answered)return;let q=QUESTION_BANK[state.index],wrong=state.selected!==q.answer,before=state.health,risk=wrong?riskOf(q.effect):null;if(wrong)state.wrongChain=0;previousSubmit();if(!wrong)return;state.wrongChain=1;state.health=Math.max(0,before-risk.damage);status();avatar(q.effect);impact(q.effect,risk,before);el.feedbackLabel.textContent=`${risk.label.toUpperCase()} PATHOLOGY`;el.consequence.innerHTML=`<b style="color:${risk.color}">${risk.label} −${risk.damage} CONDITION</b>｜${q.effect.detail}<br><small>${risk.note}。ダメージは連続ミス数ではなく病態の危険度で決まります。</small>`;let newest=state.records[0];if(newest){newest.result=`${risk.label}（−${risk.damage}）：${q.effect.name}／${q.effect.detail}`;records()}let pill=$("#clinicalSeverity");if(pill){pill.textContent=risk.label;pill.style.background=risk.color}if(state.health<=0)setTimeout(death,500)};
el.submit.onclick=submit;
})();
