// 疾患・病態・緊急対応に限定した出題パック。
const DISEASE_IDS=new Set(["115-B014","115-B015","115-B016","115-B017","115-B022","115-B023","115-B025","115-B013","115-B029","115-B030"]);
const diseaseQuestions=[
{id:"115-B034",source:"第115回 午後 34",category:"脳・神経",difficulty:2,scenario:"脳梗塞／利き手の片麻痺",question:"食事の自助具を選ぶため、優先して連携する専門職はどれか。",choices:["義肢装具士","作業療法士","臨床工学技士","医療ソーシャルワーカー"],answer:1,explanation:"食事など日常生活動作に用いる自助具の選定・練習は、作業療法士が専門性を発揮する領域です。",notes:["義肢・装具の製作などを担います。","正解。日常生活動作を評価・支援します。","医療機器の操作・保守などを担います。","社会資源の調整などを担います。"],effect:{name:"脳梗塞症状",detail:"片側の手足が動かしにくい",damage:18,pulse:18,spo2:-2,focus:22,className:"critical"}},
{id:"115-B035",source:"第115回 午後 35",category:"脳・神経",difficulty:2,scenario:"コミュニケーション障害",question:"コミュニケーションの方法として筆談が適しているのはどれか。",choices:["全失語","構音障害","運動性失語","感覚性失語"],answer:1,explanation:"構音障害では言語の理解や文字表出が保たれている場合があり、発声・発音の代替として筆談が有効です。",notes:["読み書きも障害され得ます。","正解。発音の障害を文字で補えます。","書字も障害されることがあります。","言語理解自体が障害されます。"],effect:{name:"構音障害",detail:"言葉をうまく発音できない",damage:13,pulse:10,spo2:0,focus:18,className:"blur"}},
{id:"115-B038",source:"第115回 午後 38",category:"呼吸器",difficulty:2,scenario:"閉塞性換気障害",question:"口すぼめ呼吸によって生じるのはどれか。",choices:["気道内圧の上昇","呼吸回数の増加","末梢気道の閉塞","1回換気量の減少"],answer:0,explanation:"口すぼめ呼吸は呼気時の気道内圧を高め、末梢気道の虚脱を防いで呼気をしやすくします。",notes:["正解。呼気時に陽圧がかかります。","通常はゆっくりした呼吸を促します。","閉塞を防ぐ目的です。","呼気を改善する呼吸法です。"],effect:{name:"呼吸困難",detail:"呼気が長くなり息が吐けない",damage:22,pulse:30,spo2:-10,focus:24,className:"hypoxia"}},
{id:"115-B040",source:"第115回 午後 40",category:"救急",difficulty:2,scenario:"一次救命処置〈BLS〉",question:"心停止と判断する徴候はどれか。",choices:["奇脈","昏睡","死戦期呼吸","四肢のチアノーゼ"],answer:2,explanation:"反応がなく、正常な呼吸がない、または死戦期呼吸のみの場合は心停止として胸骨圧迫を開始します。",notes:["心停止そのものの判断徴候ではありません。","昏睡だけでは判断しません。","正解。正常な呼吸とは扱いません。","心停止前にも生じ得ます。"],effect:{name:"心停止",detail:"脈拍が消失し死戦期呼吸になった",damage:32,pulse:45,spo2:-18,focus:35,className:"critical"}},
{id:"115-B046",source:"第115回 午後 46",category:"救急・中毒",difficulty:3,scenario:"有機リン中毒／流涎・縮瞳・呼吸困難",question:"直ちに投与される薬剤はどれか。",choices:["ビタミンK製剤","オキシコドン塩酸塩","バンコマイシン塩酸塩","アトロピン硫酸塩水和物"],answer:3,explanation:"有機リン中毒のムスカリン症状にはアトロピンを用います。呼吸管理と除染も重要です。",notes:["凝固因子関連の治療薬です。","オピオイド鎮痛薬です。","抗菌薬です。","正解。ムスカリン作用に拮抗します。"],effect:{name:"有機リン中毒",detail:"縮瞳・流涎・呼吸困難が出現",damage:30,pulse:38,spo2:-15,focus:30,className:"critical"}},
{id:"115-B048",source:"第115回 午後 48",category:"循環器",difficulty:2,scenario:"不安定狭心症／硝酸薬の指導",question:"胸痛発作時に用いる硝酸薬の説明で正しいのはどれか。",choices:["冷蔵庫で保存する","使用15分程度で効果が出る","痛みが強ければかみ砕く","使用後は急に立ち上がらない"],answer:3,explanation:"硝酸薬は血管拡張により血圧低下や立ちくらみを起こすため、使用後は急に立ち上がらないよう説明します。",notes:["一般に冷蔵保存とは限りません。","舌下薬はより速やかな作用を期待します。","指示された方法で使用します。","正解。転倒予防にも重要です。"],effect:{name:"狭心症発作",detail:"胸部圧迫感と冷汗が出現",damage:24,pulse:34,spo2:-5,focus:26,className:"critical"}},
{id:"115-B049",source:"第115回 午後 49",category:"消化器・がん",difficulty:2,scenario:"肝動脈塞栓術〈TAE〉",question:"TAEの適応となる疾患はどれか。",choices:["肝囊胞","脂肪肝","肝細胞癌","急性A型肝炎"],answer:2,explanation:"肝細胞癌は主に肝動脈から血流を受けるため、腫瘍への血流を遮断する肝動脈塞栓術が用いられます。",notes:["通常の適応ではありません。","通常の適応ではありません。","正解。代表的な適応疾患です。","通常の適応ではありません。"],effect:{name:"肝機能障害",detail:"黄疸と強い倦怠感が出現",damage:18,pulse:14,spo2:-2,focus:24,className:"blur"}},
{id:"115-B050",source:"第115回 午後 50",category:"膠原病",difficulty:2,scenario:"多発性筋炎",question:"多発性筋炎の症状として正しいのはどれか。",choices:["両頰の紅斑","足関節が動かせない","物を持ち上げられない","温熱刺激で手指が白色になる"],answer:2,explanation:"多発性筋炎では近位筋優位の筋力低下がみられ、腕を上げる、物を持ち上げるなどが難しくなります。",notes:["皮膚筋炎などでみられる所見です。","典型的な表現ではありません。","正解。近位筋力低下を反映します。","典型的なレイノー現象の説明ではありません。"],effect:{name:"近位筋力低下",detail:"腕が上がらず物を持てない",damage:15,pulse:12,spo2:0,focus:15,className:""}},
{id:"115-B052",source:"第115回 午後 52",category:"耳鼻科",difficulty:2,scenario:"Ménière〈メニエール〉病",question:"メニエール病で正しいのはどれか。",choices:["耳鳴を伴う","70歳以上で好発する","浮動性めまいが出現する","蝸牛の機能は保たれる"],answer:0,explanation:"メニエール病では反復する回転性めまいに、難聴・耳鳴・耳閉感などの聴覚症状を伴います。",notes:["正解。代表的な随伴症状です。","特定の70歳以上に限りません。","典型的には回転性めまいです。","感音難聴を伴い得ます。"],effect:{name:"メニエール病",detail:"回転性めまいと耳鳴が出現",damage:17,pulse:16,spo2:0,focus:30,className:"blur"}},
{id:"115-B053",source:"第115回 午後 53",category:"泌尿器・がん",difficulty:2,scenario:"膀胱癌／術前",question:"緊急の対応が必要な症状はどれか。",choices:["残尿感","尿閉","排尿痛","頻尿"],answer:1,explanation:"尿閉は尿を排出できない状態で、膀胱過伸展や腎機能への影響を避けるため速やかな評価と対応が必要です。",notes:["評価は必要ですが尿閉より緊急度は低いです。","正解。完全に排尿できない状態です。","評価は必要ですが尿閉より緊急度は低いです。","評価は必要ですが尿閉より緊急度は低いです。"],effect:{name:"急性尿閉",detail:"下腹部が張り尿が出ない",damage:21,pulse:28,spo2:0,focus:24,className:"critical"}},
{id:"115-B061",source:"第115回 午後 61",category:"小児・感染症",difficulty:2,scenario:"学校感染症",question:"出席停止基準の説明で正しいのはどれか。",choices:["麻しんは解熱するまで","伝染性紅斑は紅斑消失まで","水痘は発疹がすべて痂皮化するまで","流行性耳下腺炎は腫脹消失後7日まで"],answer:2,explanation:"水痘は、すべての発疹が痂皮化するまで出席停止となります。疾患ごとに基準が異なります。",notes:["解熱後の所定期間も考慮します。","一律に紅斑消失までではありません。","正解。すべての発疹の痂皮化が基準です。","腫脹発現後の日数など所定条件があります。"],effect:{name:"水痘",detail:"全身に発熱と水疱が広がった",damage:16,pulse:20,spo2:-2,focus:18,className:"critical"}},
{id:"115-B080",source:"第115回 午後 80",category:"腎・泌尿器",difficulty:3,scenario:"急性腎不全",question:"急性腎不全の症状として正しいのはどれか。",choices:["関節痛","頻呼吸","食欲増進","視力低下","足のムズムズ"],answer:1,explanation:"急性腎不全では代謝性アシドーシスや肺水腫などにより頻呼吸を生じることがあります。尿量、電解質、呼吸状態を観察します。",notes:["代表的症状ではありません。","正解。酸塩基平衡や体液過剰に関連します。","食欲は低下し得ます。","代表的症状ではありません。","代表的症状ではありません。"],effect:{name:"急性腎不全",detail:"尿量が減り呼吸が速くなった",damage:25,pulse:32,spo2:-10,focus:28,className:"critical"}}
];
window.QUESTION_BANK=[...window.QUESTION_BANK.filter(q=>DISEASE_IDS.has(q.id)),...diseaseQuestions];
