const baseSubmit=submit,baseDeath=death;
submit=function(){if(state.selected===null||state.answered)return;let q=QUESTION_BANK[state.index],correct=state.selected===q.answer;baseSubmit();sound(correct?"ok":"wrong");if(!correct){el.feedbackLabel.textContent="PATHOLOGY SIMULATION ACTIVE";el.feedbackTitle.textContent=`${q.effect.name}を身体に疑似再現`;el.consequence.textContent=el.consequence.textContent.replace("CONDITION","SIMULATION LOAD");if(state.records[0]){state.records[0].result=`病態リンク：${q.effect.name}を疑似再現／${q.effect.detail}`;records()}}if(correct&&state.streak>=3&&state.symptoms.length){state.symptoms.pop();state.health=Math.min(100,state.health+5);el.consequence.textContent+=" 連続正解で病態リンクを1つ解除し、耐性が5回復。";status();avatar(null)}};
death=function(){sound("death");$("#finalTotal").textContent=QUESTION_BANK.length;$("#reviewButton").hidden=!state.review.length;baseDeath();$("#resultEyebrow").textContent="SIMULATION OVERLOAD";$("#resultTitle").textContent="疑似病態が限界を超えた";$("#resultMessage").textContent="病気になったのではなく、複数の病態シミュレーション負荷に耐えられなくなった状態です。記録から誤った判断を確認してください。"};
finish=function(){let ratio=state.score/QUESTION_BANK.length;$("#finalScore").textContent=state.score;$("#finalTotal").textContent=QUESTION_BANK.length;$("#finalHealth").textContent=state.health;$("#reviewCount").textContent=state.review.length;$("#reviewButton").hidden=!state.review.length;$("#resultMessage").textContent=ratio>=.8?"病態の連鎖を断ち切りました。根拠のある判断ができています。":ratio>=.5?"夜勤完了。誤答症例を確認しましょう。":"症状が蓄積しました。間違いだけ復習して立て直しましょう。";el.modal.hidden=false;save()};
function startReview(){let ids=new Set(state.review),missed=fullBank.filter(q=>ids.has(q.id));if(!missed.length)return;QUESTION_BANK=shuffle(missed);reset();$("#resultEyebrow").textContent="REVIEW SHIFT";$("#finalTotal").textContent=QUESTION_BANK.length}
function startFull(){QUESTION_BANK=shuffle([...fullBank]).slice(0,20);reset();$("#finalTotal").textContent=QUESTION_BANK.length}
el.submit.onclick=submit;$("#reviewButton").onclick=startReview;$("#retryButton").onclick=startFull;
$("#soundButton").onclick=e=>{soundOn=!soundOn;e.currentTarget.textContent=soundOn?"♪":"♪×";e.currentTarget.classList.toggle("sound-on",soundOn);e.currentTarget.setAttribute("aria-label",soundOn?"サウンドをオフにする":"サウンドをオンにする");if(soundOn)tone(660,.12)};
QUESTION_BANK=shuffle([...fullBank]).slice(0,20);$("#finalTotal").textContent=QUESTION_BANK.length;render();

function showTitle(){el.modal.hidden=true;$("#gameShell").classList.add("game-hidden");$("#titleScreen").hidden=false;window.scrollTo({top:0,behavior:"smooth"})}
function beginShift(){startFull();$("#titleScreen").hidden=true;$("#gameShell").classList.remove("game-hidden");window.scrollTo({top:0,behavior:"smooth"})}
$("#startGame").onclick=beginShift;$("#howButton").onclick=()=>$("#howPanel").hidden=false;$("#howClose").onclick=()=>$("#howPanel").hidden=true;$("#howPanel").onclick=e=>e.stopPropagation();$(".brand").onclick=e=>{e.preventDefault();showTitle()};
const prior=JSON.parse(localStorage.getItem("recare-last")||"null");if(prior){let date=new Date(prior.date).toLocaleDateString("ja-JP"),total=prior.records?.length||20;$("#lastResult").innerHTML=`<span>LAST RECORD</span><b>${date} · ${prior.score}/${total}正解 · 要復習${prior.review?.length||0}</b>`}
