(()=>{
function announce(text){let live=$("#appLive");if(!live){live=document.createElement("div");live.id="appLive";live.setAttribute("aria-live","polite");live.style.cssText="position:fixed;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)";document.body.appendChild(live)}live.textContent="";setTimeout(()=>live.textContent=text,30)}
function syncUI(state){let chip=$("#syncState");if(!chip)return;chip.className=`sync-state ${state}`;chip.textContent=state==="syncing"?"同期中":state==="saved"?"同期済み":state==="error"?"同期エラー":state==="offline"?"オフライン":"端末保存"}
function notice(text){document.querySelector(".network-toast")?.remove();let n=document.createElement("div");n.className="network-toast";n.textContent=text;document.body.appendChild(n);setTimeout(()=>n.remove(),3000)}
function inject(){el.feedback.setAttribute("aria-live","polite");el.avatarStage.setAttribute("tabindex","-1");let account=document.querySelector(".account-chip");if(account){account.insertAdjacentHTML("beforeend",`<span class="sync-state" id="syncState">${window.RECARE_CLOUD?.enabled()?"接続済み":"端末保存"}</span>`);syncUI(navigator.onLine?(window.RECARE_CLOUD?.enabled()?"saved":"local"):"offline")}document.body.insertAdjacentHTML("beforeend",`<button class="mobile-anatomy-jump" id="anatomyJump" type="button"><b id="anatomyCount">0</b>人体模型を見る</button>`);$("#anatomyJump").onclick=()=>{el.avatarStage.scrollIntoView({behavior:"smooth",block:"center"});setTimeout(()=>el.avatarStage.focus({preventScroll:true}),450)}}
const oldAvatar=avatar;avatar=function(effect){oldAvatar(effect);let count=state.anatomyEpisodes?.length||0,jump=$("#anatomyJump");if(jump){$("#anatomyCount").textContent=count;jump.classList.toggle("has-symptom",count>0);jump.setAttribute("aria-label",`人体模型を見る。発症中の病態${count}件`)}};
const oldSubmit=submit;submit=function(){let selected=state.selected,q=QUESTION_BANK[state.index];oldSubmit();if(selected===null)return;announce(state.answered?`${selected===q.answer?"正解":"不正解"}。${q.explanation}`:"");setTimeout(()=>el.next.hidden?null:el.next.focus(),250)};el.submit.onclick=submit;
window.addEventListener("recare-cloud-status",e=>{syncUI(e.detail);if(e.detail==="error")notice("同期できませんでした。記録は端末に保持しています。")});window.addEventListener("offline",()=>{syncUI("offline");notice("オフラインです。記録は接続後に同期されます。")});window.addEventListener("online",()=>{syncUI(window.RECARE_CLOUD?.enabled()?"saved":"local");notice("オンラインに復帰しました。")});
inject();avatar(null);
})();
