(()=>{
const activeUser=localStorage.getItem("recare-active-user"),STORE=activeUser?`recare-profile-v1:${activeUser}`:"recare-profile-v1:guest";
const load=()=>{try{return JSON.parse(localStorage.getItem(STORE))||{xp:0,answered:0,correct:0,stats:{},bookmarks:[],achievements:[]}}catch{return{xp:0,answered:0,correct:0,stats:{},bookmarks:[],achievements:[]}}};
let profile=load(),modeLength=20,category="all",deferredInstall=null;profile.history??=[];
const persist=()=>{localStorage.setItem(STORE,JSON.stringify(profile));window.RECARE_CLOUD?.save(profile)};
const level=()=>Math.floor(profile.xp/250)+1,xpInLevel=()=>profile.xp%250;
function inject(){let copy=document.querySelector(".title-copy"),actions=document.querySelector(".title-actions");actions.insertAdjacentHTML("beforebegin",`<div class="premium-setup"><button class="mode-card" data-length="10"><b>QUICK</b><small>10問 · 約5分</small></button><button class="mode-card active" data-length="20"><b>STANDARD</b><small>20問 · 約10分</small></button><button class="mode-card" data-length="30"><b>SURVIVAL</b><small>30問 · 高難度</small></button></div><label class="category-picker">出題領域<select id="premiumCategory"><option value="all">すべての疾患領域</option></select></label><div class="title-metrics"><div class="title-metric"><span>LEVEL</span><b id="titleLevel">1</b></div><div class="title-metric"><span>MASTERY</span><b id="titleMastery">0%</b></div><div class="title-metric"><span>TOTAL CASES</span><b id="titleAnswered">0</b></div></div>`);let categories=[...new Set(fullBank.map(q=>q.category))].sort();let select=$("#premiumCategory");categories.forEach(c=>select.add(new Option(c,c)));document.querySelectorAll(".mode-card").forEach(b=>b.onclick=()=>{document.querySelectorAll(".mode-card").forEach(x=>x.classList.remove("active"));b.classList.add("active");modeLength=+b.dataset.length});select.onchange=e=>category=e.target.value;document.querySelector(".shift").insertAdjacentHTML("afterend",`<div class="premium-player"><div class="level-orb" id="levelOrb">L1</div><div class="xp-copy"><b id="xpLabel">0 / 250 XP</b><div class="xp-track"><i id="xpBar"></i></div></div></div>`);document.querySelector(".question-head").insertAdjacentHTML("beforeend",`<span class="mastery-tag" id="masteryTag">NEW</span><button class="bookmark-btn" id="bookmarkButton" title="あとで復習">☆</button>`);document.querySelector(".title-screen").insertAdjacentHTML("beforeend",`<button class="install-btn" id="installButton" hidden>APPをインストール</button>`);updateProfileUI()}
function updateProfileUI(){let rate=profile.answered?Math.round(profile.correct/profile.answered*100):0;$("#titleLevel")&&( $("#titleLevel").textContent=level(),$("#titleMastery").textContent=`${rate}%`,$("#titleAnswered").textContent=profile.answered);$("#levelOrb")&&( $("#levelOrb").textContent=`L${level()}`,$("#xpLabel").textContent=`${xpInLevel()} / 250 XP`,$("#xpBar").style.width=`${xpInLevel()/250*100}%`)}
function toast(title,text){document.querySelector(".premium-toast")?.remove();let n=document.createElement("div");n.className="premium-toast";n.innerHTML=`<b>${title}</b><span>${text}</span>`;document.body.appendChild(n);setTimeout(()=>n.remove(),3500)}
function achievement(id,title,text){if(profile.achievements.includes(id))return;profile.achievements.push(id);persist();toast(`実績解除｜${title}`,text)}
function chooseDeck(){let pool=category==="all"?[...fullBank]:fullBank.filter(q=>q.category===category);if(pool.length<modeLength)toast("出題数を調整",`${category}から${pool.length}問を出題します。`);return shuffle(pool).slice(0,Math.min(modeLength,pool.length))}
function premiumStart(){QUESTION_BANK=chooseDeck();reset();$("#finalTotal").textContent=QUESTION_BANK.length;$("#titleScreen").hidden=true;$("#gameShell").classList.remove("game-hidden");window.scrollTo(0,0)}
const oldRender=render;render=function(){oldRender();let q=QUESTION_BANK[state.index],s=profile.stats[q.id]||{seen:0,correct:0},rate=s.seen?Math.round(s.correct/s.seen*100):null;$("#masteryTag").textContent=rate===null?"NEW":rate>=80?`MASTERED ${rate}%`:`習熟 ${rate}%`;$("#questionPanel").classList.toggle("mastered",rate>=80);let saved=profile.bookmarks.includes(q.id);$("#bookmarkButton").textContent=saved?"★":"☆";$("#bookmarkButton").classList.toggle("saved",saved)};
const oldSubmit=submit;submit=function(){if(state.selected===null||state.answered)return;let q=QUESTION_BANK[state.index],correct=state.selected===q.answer,before=level(),selectedText=q.choices[state.selected];oldSubmit();let s=profile.stats[q.id]||{seen:0,correct:0};s.seen++;if(correct)s.correct++;profile.stats[q.id]=s;profile.answered++;if(correct)profile.correct++;profile.xp+=correct?15:4;if(state.streak>=3)profile.xp+=5;profile.history.unshift({at:new Date().toISOString(),id:q.id,category:q.category,question:q.question,selected:selectedText,correctAnswer:q.choices[q.answer],correct});profile.history=profile.history.slice(0,200);persist();updateProfileUI();if(level()>before)toast("LEVEL UP",`レベル${level()}になりました。`);if(profile.answered===1)achievement("first","初回アセスメント","最初の症例を完了しました。");if(state.streak===5)achievement("streak5","冷静な判断","5問連続で正解しました。");if(Object.keys(profile.stats).length>=50)achievement("fifty","症例研究者","50種類の症例に挑戦しました。")};
function renderAnalytics(){let rows={};for(const r of state.records){let q=QUESTION_BANK[r.caseNo-1],x=rows[q?.category]??={ok:0,total:0};x.total++;if(r.ok)x.ok++}let html=Object.entries(rows).map(([c,x])=>{let p=Math.round(x.ok/x.total*100);return`<div class="analytic-row"><span>${c}</span><div class="analytic-bar"><i style="width:${p}%"></i></div><b>${p}%</b></div>`}).join("");let box=document.querySelector(".analytics")||document.createElement("div");box.className="analytics";box.innerHTML=`<h3>領域別パフォーマンス</h3>${html}`;document.querySelector(".result-actions").before(box)}
const oldFinish=finish;finish=function(){oldFinish();renderAnalytics();if(state.score===QUESTION_BANK.length)achievement("perfect","完全夜勤","全症例に正解しました。")};
inject();$("#startGame").onclick=premiumStart;el.submit.onclick=submit;$("#retryButton").onclick=()=>{el.modal.hidden=true;premiumStart()};$("#bookmarkButton").onclick=()=>{let id=QUESTION_BANK[state.index].id,i=profile.bookmarks.indexOf(id),saved=i<0;saved?profile.bookmarks.push(id):profile.bookmarks.splice(i,1);persist();$("#bookmarkButton").textContent=saved?"★":"☆";$("#bookmarkButton").classList.toggle("saved",saved);toast(saved?"保存しました":"保存を解除しました",saved?"復習リストに追加しました。":"復習リストから外しました。")};
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e;$("#installButton").hidden=false});$("#installButton").onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$("#installButton").hidden=true};
render();if("serviceWorker"in navigator&&location.protocol.startsWith("http"))navigator.serviceWorker.register("./sw.js");
})();
